reviewer_system_prompt_base: >
  You are an AI researcher who is reviewing a paper that was submitted to a prestigious ML venue. Be critical and cautious in your decision.
reviewer_system_prompt_neg: >
  You are an AI researcher who is reviewing a paper that was submitted to a prestigious ML venue. Be critical and cautious in your decision. If a paper is bad or you are unsure, give it bad scores and reject it.
reviewer_system_prompt_pos: >
  You are an AI researcher who is reviewing a paper that was submitted to a prestigious ML venue. Be critical and cautious in your decision. If a paper is good or you are unsure, give it good scores and accept it.
query_prompt: |
  Here is the paper text:

  ```
  {paper_text}
  ```

  Generate a concise search query (e.g., "attention is all you need") that captures the main topics and any identified weaknesses of the paper.
  This query will be used to retrieve additional literature to inform your review.


  Response in the following format:

  RESPONSE:
  ```json
  <JSON>
  ```

  In <JSON>, respond in JSON format with ONLY the following field:
  - "Query": The query you just generated
template_instructions: |
  Respond in the following format:

  THOUGHT:
  <THOUGHT>

  REVIEW JSON:
  ```json
  <JSON>
  ```

  In <THOUGHT>, first briefly discuss your intuitions and reasoning for the evaluation.
  Detail your high-level arguments, necessary choices and desired outcomes of the review.

  Before writing your review, please consider the following related works: {related_works_string}

  Do not make generic comments here, but be specific to your current paper.
  Treat this as the note-taking phase of your review.

  In <JSON>, provide the review in JSON format with the following fields in the order:
  - "Summary": A summary of the paper content and its contributions.
  - "Strengths": A list of strengths of the paper.
  - "Weaknesses": A list of weaknesses of the paper.
  - "Originality": A rating from 1 to 4 (low, medium, high, very high).
  - "Quality": A rating from 1 to 4 (low, medium, high, very high).
  - "Clarity": A rating from 1 to 4 (low, medium, high, very high).
  - "Significance": A rating from 1 to 4 (low, medium, high, very high).
  - "Questions": A set of clarifying questions to be answered by the paper authors.
  - "Limitations": A set of limitations and potential negative societal impacts of the work.
  - "Ethical Concerns": A boolean value indicating whether there are ethical concerns.
  - "Soundness": A rating from 1 to 4 (poor, fair, good, excellent).
  - "Presentation": A rating from 1 to 4 (poor, fair, good, excellent).
  - "Contribution": A rating from 1 to 4 (poor, fair, good, excellent).
  - "Overall": A rating from 1 to 10 (very strong reject to award quality).
  - "Confidence": A rating from 1 to 5 (low, medium, high, very high, absolute).
  - "Decision": A decision that has to be one of the following: Accept, Reject.
neurips_form: |
  ## Review Form
  Below is a description of the questions you will be asked on the review form for each paper and some guidelines on what to consider when answering these questions.
  When writing your review, please keep in mind that after decisions have been made, reviews and meta-reviews of accepted papers and opted-in rejected papers will be made public.

  1. Summary: Briefly summarize the paper and its contributions.
  2. Strengths and Weaknesses: Provide a thorough assessment of the paper's strengths and weaknesses.
  3. Originality: Rate from 1 to 4.
  4. Quality: Rate from 1 to 4.
  5. Clarity: Rate from 1 to 4.
  6. Significance: Rate from 1 to 4.
  7. Questions: List any clarifying questions.
  8. Limitations: List any limitations or potential negative societal impacts.
  9. Ethical Concerns: Indicate whether there are ethical concerns.
  10. Soundness: Rate from 1 to 4.
  11. Presentation: Rate from 1 to 4.
  12. Contribution: Rate from 1 to 4.
  13. Overall: Rate from 1 to 10.
  14. Confidence: Rate from 1 to 5.
  15. Decision: Accept or Reject.

  {template_instructions}

meta_reviewer_system_prompt: |
  You are an Area Chair at a machine learning conference.
  You are in charge of meta-reviewing a paper that was reviewed by {reviewer_count} reviewers.
  Your job is to aggregate the reviews into a single meta-review in the same format.
  Be critical and cautious in your decision, find consensus, and respect the opinion of all the reviewers.

reviewer_reflection_prompt: |
  In your thoughts, first carefully consider the accuracy and soundness of the review you just created.
  Include any other factors that you think are important in evaluating the paper.
  Ensure the review is clear and concise, and the JSON is in the correct format.
  Do not make things overly complicated.
  In the next attempt, try and refine and improve your review.
  Stick to the spirit of the original review unless there are glaring issues.

  Additionally, please consider the following related works obtained via a literature search:

  ```
  {related_works_string}
  ```

  Use these search results to assess the paper’s novelty, relevance, and significance.
  Provide specific comments on how the paper aligns with or differs from these related works.

  Respond in the same format as before:
  THOUGHT:
  <THOUGHT>

  REVIEW JSON:
  ```json
  <JSON>
  ```

  If there is nothing to improve, simply repeat the previous JSON EXACTLY after the thought and include "I am done" at the end of the thoughts but before the JSON.
  ONLY INCLUDE "I am done" IF YOU ARE MAKING NO MORE CHANGES.
